In [1]:
import os
import tweepy as tw
import pandas as pd

In [2]:
consumer_key= 'tprwF9XOmFWxCqk8k0JqL6SXd'
consumer_secret= '2NIajOzhv03oJBERTtLzvsHLbVSqMlNLDcbWz2kJD42jlVDqgp'
access_token= '1284839505955106816-F9Dfbfo7TPHVBAkCaHg6ncjqV0RdWi'
access_token_secret= 'HDU7T2vEqXgB87kXurqtJqF6fNEEjRAMxXGvZQGUGpDV7'

In [3]:
auth = tw.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tw.API(auth, wait_on_rate_limit=True)

In [11]:
search_words = "Stacey Abrams" +  " -filter:retweets"
date_since = "2021-01-06"

In [67]:
tweets = tw.Cursor(api.search, 
                           q=search_words,
                           lang="en",
                           since=date_since).items(2000)

In [68]:
stacey_tweets = [[tweet.favorite_count, tweet.retweet_count, tweet.text, tweet.user.location] for tweet in tweets]

In [69]:
adams_df = pd.DataFrame(data=stacey_tweets, 
                    columns=["Likes", "Retweets", "Text", "User Location"])

In [70]:
adams_df

,Likes,Retweets,Text,User Location
0,0,0,@VotesAmelia Stacey Abrams is far more deservi...,"Ontario, Canada"
1,0,0,Everything Ms. Abrams suggests here is both cr...,"Kyoto, Japan"
2,0,0,https://t.co/GcYzjezZej\nOpinion | Stacey Abra...,Maryland
3,3,0,They need to have Stacey Abrams work on these...,
4,0,0,Please read and share..Stacey Abrams: Our demo...,Crestview Florida...gulf coast
...,...,...,...,...
1995,1,0,Stacey Abrams Receives Well Deserved Nobel Pea...,"Atlanta, Ga"
1996,0,2,Conservatives WILL NOT win in 2022 if we do no...,
1997,0,0,Republicans have a way bigger problem than the...,
1998,2,2,"Stacey ""I'm An Idiot"" Abrams Has Been Nominate...",United States
1999,8,0,@GlennonDoyle @__shakti_ Come to Georgia. We h...,

In [71]:
senate_words = "Senate" +  " -filter:retweets"

In [72]:
tweets = tw.Cursor(api.search, 
                           q=senate_words,
                           lang="en",
                           since=date_since).items(2000)

In [73]:
senate_tweets = [[tweet.favorite_count, tweet.retweet_count, tweet.text, tweet.user.location] for tweet in tweets]

In [74]:
senate_df = pd.DataFrame(data=senate_tweets, 
                    columns=["Likes", "Retweets", "Text", "User Location"])

In [75]:
senate_df

,Likes,Retweets,Text,User Location
0,0,0,Now performing: @theweeknd and the imperial se...,
1,1,0,alright I'm heading to bed early tonight so!\n...,any pronouns ❤️
2,0,0,@mmpadellan Over there acting like the Republi...,N. California
3,0,0,My favorite part of the #SuperBowlHalftimeShow...,"It's not that bad, Kansas"
4,0,0,Is @theweeknd performing in front of the Senat...,
...,...,...,...,...
1995,0,0,I can't understand why a relative of one of th...,
1996,3,2,@SenatorDurbin @ndaajustice @POTUS Dear @Senat...,Le Monde
1997,0,0,@CREWcrew That’s sacrificing their own wealth ...,
1998,0,0,"@SenSasse $10,000 DERSHOWITZ CHALLENGE\n\nProf...",Castro Valley
1999,1,0,@Lorrain22492203 @LindseyGrahamSC South Caroli...,

In [76]:
capitol_words = "Capitol" +  " -filter:retweets"

In [77]:
tweets = tw.Cursor(api.search, 
                           q=capitol_words,
                           lang="en",
                           since=date_since).items(2000)

In [78]:
capitol_tweets = [[tweet.favorite_count, tweet.retweet_count, tweet.text, tweet.user.location] for tweet in tweets]

In [79]:
capitol_df = pd.DataFrame(data=capitol_tweets, 
                    columns=["Likes", "Retweets", "Text", "User Location"])

In [80]:
capitol_df

,Likes,Retweets,Text,User Location
0,0,0,this was AOC trying to find mitch mcconnell in...,onyx hotel
1,0,0,Love ❤️ Jake Tapper! issues warning to GOP ab...,"Palos Hills, IL"
2,0,0,@teagiver7 @A_Wonderful_Lif @SusanLe11666982 @...,
3,0,0,Why was he flagged for having Brady rush like ...,"Boston,MA--56ace,FL"
4,0,0,This how they were walking around the capitol ...,
...,...,...,...,...
1995,0,0,@flowershark @BillyGBolton @nx6QiUa5V9rrbUX @m...,
1996,0,0,Keine Satire btw\n\nhttps://t.co/W9dE1Eu8mo,
1997,0,0,https://t.co/wiYbVUZEOA Nicholas Fandos The ou...,
1998,98,8,@DonaldJTrumpJr Donald Trump is GUILTY!!!\n\nD...,89135
1999,0,0,GOP registration drop after Capitol attack is ...,"South Carolina, USA"

In [81]:
dems_words = "Dems" +  " -filter:retweets"

In [82]:
tweets = tw.Cursor(api.search, 
                           q=dems_words,
                           lang="en",
                           since=date_since).items(2000)

In [83]:
dems_tweets = [[tweet.favorite_count, tweet.retweet_count, tweet.text, tweet.user.location] for tweet in tweets]

In [84]:
dems_df = pd.DataFrame(data=dems_tweets, 
                    columns=["Likes", "Retweets", "Text", "User Location"])

In [85]:
dems_df

,Likes,Retweets,Text,User Location
0,0,0,"@tedcruz Yeah, crazy Dems...what do you have a...","Catalina Foothills, AZ"
1,0,0,First time in history many not watching.\nDemo...,
2,0,0,@JessTurnr I used to hold Superbowl parties. W...,
3,0,0,Dems Have a Mandate—Why Won’t They Use It?\nht...,"New York, NY"
4,0,0,.@JoeBiden please keep fighting for $15 minimu...,"Minnesota, USA"
...,...,...,...,...
1995,0,0,@tedcruz So all those folks tearing apart the ...,
1996,2,0,@thehill The reality is that over and over aga...,"New York, NY"
1997,0,0,@mtgreenee The Dems won’t destroy you. You’ll ...,"Massachusetts, USA"
1998,2,1,@MollyJongFast Ted Cruz - chief among the vote...,USA
1999,0,0,@KeathMayes @Ellimem @PatrickDHogan @kylegriff...,New Orleanian in exile.

In [86]:
democrats_words = "Democrats"  +  " -filter:retweets"

In [87]:
tweets = tw.Cursor(api.search, 
                           q=democrats_words,
                           lang="en",
                           since=date_since).items(2000)

In [88]:
democrats_tweets = [[tweet.favorite_count, tweet.retweet_count, tweet.text, tweet.user.location] for tweet in tweets]

In [89]:
democrats_df = pd.DataFrame(data=democrats_tweets, 
                    columns=["Likes", "Retweets", "Text", "User Location"])

In [90]:
democrats_df

,Likes,Retweets,Text,User Location
0,0,0,@kylegriffin1 @bethlevin The GOP has been clai...,New York City
1,0,0,People are packing a stadium for a fucking stu...,
2,0,0,"@thehill When Trump was in office, you showed ...",
3,7,2,Democrats at 4am when Trump was ahead by milli...,Ohio
4,0,0,"@BaiamonteEdward @reveralife @jasin_chang No, ...",Caprica
...,...,...,...,...
1995,1,0,@pitchtocontact @IRaiseUFacts @ChanceRisker @y...,Between two rivers
1996,0,0,"Yeah, Democrats, or at least those who think t...","Los Angeles, CA"
1997,2,1,@harrisonjaime This was the time of the Gulf W...,
1998,1,0,@thehill The FBI proved by interviewing suspec...,Mississippi
1999,1,0,"Democrats to unveil $3,000 direct cash payment...",

In [91]:
comey_words = "Comey"  +  " -filter:retweets"

In [92]:
tweets = tw.Cursor(api.search, 
                           q=comey_words,
                           lang="en",
                           since=date_since).items(2000)

In [93]:
comey_tweets = [[tweet.favorite_count, tweet.retweet_count, tweet.text, tweet.user.location] for tweet in tweets]

In [94]:
comey_df = pd.DataFrame(data=comey_tweets, 
                    columns=["Likes", "Retweets", "Text", "User Location"])

In [95]:
comey_df

,Likes,Retweets,Text,User Location
0,0,0,INSA Leadership Dinner with FBI Director James...,30902 clubhosedr laguna niguel
1,0,0,@dhale53 @DoctorHenryCT @bevdevwarrior Only if...,"Mississippi, USA"
2,2,1,"@AuntCinnamon @BhawksGo Goodnight G Soros, Jam...","Deep South, USA"
3,2,0,@BreitbartNews Led by Comey and Clapper?,Raleigh
4,0,0,First day of intern\n*opens my mask to drink w...,
...,...,...,...,...
1995,0,0,@theMRC @birdwatch @TwitterSafety So are the d...,
1996,0,0,"@eziDOESit @UncvrngTheTruth No, Comey has been...",United States of America
1997,0,0,ANY COMPETENT PROSECUTOR COULD EASILY PROVE TO...,"Florida, USA"
1998,0,0,He does. My children are trapped in abuse they...,
1999,0,0,Fac a sex offender and he was not supposed to ...,

In [96]:
america_words = "America" +  " -filter:retweets"

In [97]:
tweets = tw.Cursor(api.search, 
                           q=america_words,
                           lang="en",
                           since=date_since).items(2000)

In [98]:
america_tweets = [[tweet.favorite_count, tweet.retweet_count, tweet.text, tweet.user.location] for tweet in tweets]

In [99]:
america_df = pd.DataFrame(data=america_tweets, 
                    columns=["Likes", "Retweets", "Text", "User Location"])

In [100]:
america_df

,Likes,Retweets,Text,User Location
0,0,0,@parkerplotkin @POTUS You do realize that Amer...,
1,0,0,I want a gc with my twitter friends but there ...,burning down Yggdrasil
2,0,0,If feel like 1/2 of America was probably like ...,"Los Angeles, CA"
3,0,0,@MattMcMuscles @Gaohmee God 7-11 has these in ...,
4,0,0,@marcuslemonis I would love to win for my daug...,United States
...,...,...,...,...
1995,0,0,Coming to America bout to be trash,"Downtown, Baltimore"
1996,1,0,Those barbers in coming to America should be d...,"Providence, RI"
1997,0,0,@TheShaunM coming to America lol,
1998,1,0,Just gonna say it. Coming 2 America is going t...,The hell I've created
1999,0,0,Soooo why does coming to America 2 have an Afr...,"Maryland, USA"

In [101]:
trump_words = "Trump" +  " -filter:retweets"

In [102]:
tweets = tw.Cursor(api.search, 
                           q=trump_words,
                           lang="en",
                           since=date_since).items(2000)

In [103]:
trump_tweets = [[tweet.favorite_count, tweet.retweet_count, tweet.text, tweet.user.location] for tweet in tweets]

In [104]:
trump_df = pd.DataFrame(data=trump_tweets, 
                    columns=["Likes", "Retweets", "Text", "User Location"])

In [105]:
trump_df

,Likes,Retweets,Text,User Location
0,0,0,Trump needs a place in a federal pen--as do yo...,
1,0,0,@LABrauer183 @BernieSanders Trump incited a ri...,
2,0,0,@RadioFreeTom Springsteen is a more credible v...,"Washington, DC"
3,0,0,Donald Trump banned from readmission to SAG-AF...,"North Carolina, USA"
4,0,0,This Jeep commercial is the worst I’ve ever se...,San Francisco
...,...,...,...,...
1995,0,0,Letter: Trump left a total mess in America for...,"Massachusetts, USA"
1996,0,0,@StephaneHus @KarstenKaren @Ms_S1954 @Sterling...,
1997,0,0,@AriMelber Having a yacht that he purchased wi...,
1998,0,0,@ShroomMeister Florida is well a....Trump stat...,
1999,2,0,@POTUS @JoeBiden Mr President you must get tho...,Los Angeles

In [106]:
john_words = "John Lewis" +  " -filter:retweets"

In [107]:
tweets = tw.Cursor(api.search, 
                           q=john_words,
                           lang="en",
                           since=date_since).items(2000)

In [ ]:
john_tweets = [[tweet.favorite_count, tweet.retweet_count, tweet.text, tweet.user.location] for tweet in tweets]

In [ ]:
john_df = pd.DataFrame(data=john_tweets, 
                    columns=["Likes", "Retweets", "Text", "User Location"])

In [ ]:
john_df

In [ ]:
caillou_words = "Caillou" +  " -filter:retweets"

In [ ]:
tweets = tw.Cursor(api.search, 
                           q=caillou_words,
                           lang="en",
                           since=date_since).items(2000)

In [ ]:
caillou_tweets = [[tweet.favorite_count, tweet.retweet_count, tweet.text, tweet.user.location] for tweet in tweets]

In [ ]:
caillou_df = pd.DataFrame(data=caillou_tweets, 
                    columns=["Likes", "Retweets", "Text", "User Location"])

In [ ]:
caillou_df

In [22]:
date_until = "2021-01-07"

In [23]:
test = tw.Cursor(api.search, 
                           q=search_words,
                           lang="en",
                           since = date_since,
                           until = date_until).items(1)

In [24]:
[tweet.text for tweet in test]

[]

In [41]:
search = "student loan forgivenss" + "-filter:retweets"

In [42]:
test = tw.Cursor(api.search, 
                           q=search,
                           lang="en",
                           since = date_since).items(10000)

In [43]:
[tweet.text for tweet in test]

['@lunadyana @AOC Bwahahhahahahahha student loan forgiveness lmao so it’s hard working peoples fault. Its not my loan… https://t.co/SmO4Ku33aK']